# final-project/kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ci
  template:
    metadata:
      labels:
        app: hello-ci
    spec:
      containers:
      - name: app
        image: IMAGE_PLACEHOLDER # <-- Our pipeline will replace this
        ports:
        - containerPort: 8080 # Let's assume our Go app will listen on 8080
