# week2/day12/event-listener.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener-secured # New name to avoid conflicts
spec:
  serviceAccountName: tekton-pipelines-controller
  triggers:
    - name: github-trigger
      interceptors: # <-- ADD THIS BLOCK
        - name: "validate-signature"
          ref:
            name: "github"
            kind: ClusterInterceptor
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
      bindings:
        - ref: github-push-binding
      template:
        ref: clone-pipeline-template
