# week2/day8/pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: conditional-ci-run-1
spec:
  pipelineRef:
    name: ci-pipeline-with-conditions
  params:
    - name: repo-url
      value: https://github.com/sudhishmk/tekton-learning.git # <-- IMPORTANT: CHANGE THIS
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-shared-workspace
